# Generated by Django 6.0.3 on 2026-03-24 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('ARQ', 'Arquero'), ('DEF', 'Defensor'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('rubro', models.CharField(choices=[('ATAQUE', 'Ataque'), ('DEFENSA', 'Defensa'), ('TECNICA', 'Técnica'), ('FISICO', 'Físico'), ('ARQUERO', 'Arquero')], max_length=10)),
                ('descripcion', models.TextField()),
                ('modificador', models.FloatField(help_text='Porcentaje (ej: 5 = 5%)')),
            ],
        ),
        migrations.CreateModel(
            name='ListaJugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_jugadores', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion_principal', models.CharField(choices=[('ARQ', 'Arquero'), ('DEF', 'Defensor'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('posicion_secundaria', models.CharField(blank=True, choices=[('ARQ', 'Arquero'), ('DEF', 'Defensor'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3, null=True)),
                ('finalizacion', models.PositiveIntegerField()),
                ('remate_cabeza', models.PositiveIntegerField()),
                ('desmarque', models.PositiveIntegerField()),
                ('vision_juego', models.PositiveIntegerField()),
                ('tiros_lejanos', models.PositiveIntegerField()),
                ('penales', models.PositiveIntegerField()),
                ('saques_esquina', models.PositiveIntegerField()),
                ('tiros_libres', models.PositiveIntegerField()),
                ('entradas', models.PositiveIntegerField()),
                ('marcaje', models.PositiveIntegerField()),
                ('anticipacion', models.PositiveIntegerField()),
                ('colocacion', models.PositiveIntegerField()),
                ('intercepciones', models.PositiveIntegerField()),
                ('despeje', models.PositiveIntegerField()),
                ('control_balon', models.PositiveIntegerField()),
                ('regate', models.PositiveIntegerField()),
                ('pases_cortos', models.PositiveIntegerField()),
                ('pases_largos', models.PositiveIntegerField()),
                ('centros', models.PositiveIntegerField()),
                ('efecto', models.PositiveIntegerField()),
                ('tecnica_disparo', models.PositiveIntegerField()),
                ('juego_espaldas', models.PositiveIntegerField()),
                ('velocidad', models.PositiveIntegerField()),
                ('aceleracion', models.PositiveIntegerField()),
                ('resistencia', models.PositiveIntegerField()),
                ('fuerza', models.PositiveIntegerField()),
                ('salto', models.PositiveIntegerField()),
                ('agilidad', models.PositiveIntegerField()),
                ('equilibrio', models.PositiveIntegerField()),
                ('potencia_salto', models.PositiveIntegerField()),
                ('reflejos', models.PositiveIntegerField(default=1)),
                ('estirada', models.PositiveIntegerField(default=1)),
                ('manejo_area', models.PositiveIntegerField(default=1)),
                ('blocaje', models.PositiveIntegerField(default=1)),
                ('saque_meta', models.PositiveIntegerField(default=1)),
                ('saque_mano', models.PositiveIntegerField(default=1)),
                ('uno_contra_uno', models.PositiveIntegerField(default=1)),
                ('comunicacion', models.PositiveIntegerField(default=1)),
                ('nivel_general', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('atributos_especiales', models.ManyToManyField(blank=True, to='lista_jugador.atributoespecial')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='lista_jugador.listajugadores')),
            ],
        ),
    ]
